version: '3'
services:
  exporter:
    container_name: exporter 
    image: ping-exporter 
    ports:
      - 8080:80
    environment:
      - PORT=80
    networks:
      - exporter 

  prometheus: 
    container_name: prometheus
    image: prom/prometheus:v2.36.2 
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml" 
      - "--storage.tsdb.path=/prometheus" 
      - "--web.console.libraries=/usr/share/prometheus/console_libraries" 
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - exporter 

networks:
  exporter:
    name: exporter 
    driver: bridge